# Dockerfile

# Use a base image with Python installed
FROM python:3.10

# Set the working directory inside the container
WORKDIR /app

# Copy the project files to the container
COPY . .

# Install project dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run Flake8 to perform linting on the project
RUN flake8

# Run pytest when the container starts
CMD ["pytest"]
